import { randomBytes } from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const envPath = resolve(process.cwd(), ".env");

function generateSecret() {
  return randomBytes(32).toString("hex");
}

function main() {
  const secretLine = `NEXTAUTH_SECRET="${generateSecret()}"`;

  if (!existsSync(envPath)) {
    const contents = [
      "# Generated by scripts/setup-env.ts",
      secretLine,
      "DATABASE_URL=\"\"",
      "OPENAI_API_KEY=\"\"",
      "",
    ].join("\n");
    writeFileSync(envPath, contents, "utf8");
    console.log("✅ Created .env with NEXTAUTH_SECRET");
    return;
  }

  const raw = readFileSync(envPath, "utf8");
  const lines = raw.split(/\r?\n/);
  const hasSecret = lines.some((l) => l.startsWith("NEXTAUTH_SECRET="));

  if (hasSecret) {
    console.log("✅ .env already has NEXTAUTH_SECRET");
    return;
  }

  const updated = [
    ...lines.filter((l) => l.trim().length > 0),
    secretLine,
    "",
  ].join("\n");

  writeFileSync(envPath, updated, "utf8");
  console.log("✅ Added NEXTAUTH_SECRET to .env");
}

main();
